PreRequisitos = {
    "Introducción a la ingeniería agronómica": [["Ninguno"]],
    "Matemáticas Básicas": [["Ninguno"]],
    "Biología de plantas": [["Ninguno"]],
    "Lecto-Escritura": [["Ninguno"]],
    "Química básica": [["Ninguno"]],
    "Cálculo diferencial": [["Ninguno"]],
    "Cálculo Integral": [["Cálculo diferencial"]],
    "Fundamentos de mecánica": [["Cálculo diferencial"]],
    "Botánica taxonómica": [["Biología de plantas"]],
    "Laboratorio de química básica": [["Ninguno"]],
    "Inglés I - Semestral": [["Examen de inglés"]],
    "Ciencia del suelo": [["Laboratorio de química básica"]],
    "Laboratorio de bioquímica básica": [["Ninguno"]],
    "Bioquímica básica": [["Química básica"]],
    "Bioestadística fundamental": [["Cálculo diferencial"]],
    "Geomática básica": [["Ninguno"]],
    "Inglés II - Semestral"  : [["Inglés I - Semestral" ]],
    "Agroclimatología": [["Ninguno"]],
    "Edafología":  [["Ciencia del suelo"]],
    "Fundamentos de ecología":    [["Ninguno"]],
    "Microbiología":    [["Ninguno"]],
    "Biología Celular y Molecular Básica":  [["Bioquímica básica"]],
    "Diseño de experimentos":[["Bioestadistica fundamental"],["Probabilidad y estadística "]],
    "Inglés III - Semestral"  : [["Inglés II - Semestral" ]],
    "Sociología Rural": [["inducción a la ingeniería agronómica"]],
    "Riegos y drenajes":[["Agroclimatología"],["Calculo Integral"],["Fundamentos de mecánica"],["Edafología"]],
    "Mecanización agrícola": [["Edafología"],["Fundamentos de mecánica"]],
    "Génetica general": [["Biología Celular y Molecular Básica"]],
    "Fisiología vegetal básica":  [["Botanica taxonómica"],["Biología Celular y Molecular Básica"],["Diseño de experimentos"]],
    "Inglés IV - Semestral"  : [["Inglés III - Semestral" ]],
    "Economía agraria": [["Calculo Integral"],["Sociología Rural"]],
    "Entomología": [["Génetica general"],["Fundamentos de ecología"]],
    "Fitopatología":    [["Fundamentos de ecología"],["Diseño de experimentos"],["Microbiología"]],
    "Fisiología de la producción vegetal":  [["Fisiología vegetal básica"]],
    "Reproducción y multiplicación": [["Fisiología vegetal básica"]],
    "Gestión agroempresarial":  [["Economia agraria"]],
    "Manejo de la fertilidad del suelo":  [["Edafología"],["Fisiología de la producción vegetal"],["Reproducción y multiplicación"]],
    "Manejo integrado de plagas": [["Entomología"],["Fisiología de la producción vegetal"]],
    "Manejo Integrado de Enfermedades":   [["Fitopatología"],["Fisiología de la producción vegetal"]],
    "Manejo integrado de malezas":   [["Fundamentos de ecología"],["Fisiología de la producción vegetal"],["Botanica taxonómica"]],
    "Ciclo i: formulación y evaluación de proyect": [["Riegos y drenajes"], ["Mecanización agrícola"], ["Manejo de la fertilidad del suelo"], ["Manejo integrado de plagas"], ["Manejo Integrado de Enfermedades"], ["Manejo integrado de malezas"]],
    "Fitomejoramiento":    [["Génetica general"],["Diseño de experimentos"]],
    "Agroecosistemas y Sistemas de Producción":[["Fisiología de la producción vegetal"],["Entomología"],["Fitopatología"],["Edafología"]],
    "Tecnología de la Poscosecha": [["Fisiologia de la producción vegetal"],["Microbiología"]],
    "Ciclo  II: Ejecución de un proyecto productiv":[["Ciclo i: formulación y evaluación de proyect"]],
    "Optativa de Producción":[["Manejo de la fertilidad del suelo"],["Manejo integrado de plagas"],["Manejo Integrado de Enfermedades"],["Manejo integrado de malezas"]],
    "Práctica Profesional":    [["Agroecosistemas y Sistemas de Producción"],["Ciclo  II: Ejecución de un proyecto productiv"]],
    "Trabajo de Grado": [["Ninguno"]]
}