prerequisitos = {'Agroclimatología': [[(('Ninguno', None), None)]],
 'Agroecosistemas y Sistemas de Producción': [[('Fisiología de la producción vegetal','2015891')],
                                              [('Entomología', '2015890')],
                                              [('Fitopatología', '2015894')],
                                              [('Edafología', '2015889')]],
 'Bioestadística fundamental': [[('Cálculo diferencial', '1000004-B')]],
 'Biología Celular y Molecular Básica': [[('Bioquímica básica', '1000042-B')]],
 'Biología de plantas': [[(('Ninguno', None), None)]],
 'Bioquímica básica': [[('Química básica', '1000041-B')]],
 'Botánica taxonómica': [[('Biología de plantas', '2015877')]],
 'Ciclo  II: Ejecución de un proyecto productiv': [[('Ciclo i: formulación y evaluación de proyect', '2015883')]],
 'Ciclo i: formulación y evaluación de proyect': [[('Riegos y drenajes','2015908')],
                                                  [('Mecanización agrícola','2015902')],
                                                  [('Manejo de la fertilidad del suelo','2015898')],
                                                  [('Manejo integrado de plagas','2015901')],
                                                  [('Manejo Integrado de Enfermedades','2015899')],
                                                  [('Manejo integrado de malezas','2015900')]],
 'Ciencia del suelo': [[('Laboratorio de química básica', '2015782')]],
 'Cálculo Integral': [[('Cálculo diferencial', '1000004-B')]],
 'Cálculo diferencial': [[(('Ninguno', None), None)]],
 'Diseño de experimentos': [[('Bioestadística fundamental', '1000012-B')],
                            [(('Probabilidad y estadística', None), None)]],
 'Economía agraria': [[('Cálculo Integral', '1000005-B')],
                      [('Sociología Rural', '2015909')]],
 'Edafología': [[('Ciencia del suelo', '2015885')]],
 'Entomología': [[('Génetica general', '2015895')],
                 [('Fundamentos de ecología', '1000011-B')]],
 'Fisiología de la producción vegetal': [[('Fisiología vegetal básica','2015892')]],
 'Fisiología vegetal básica': [[('Botánica taxonómica', '2015878')],
                               [('Biología Celular y Molecular Básica','2015882')],
                               [('Diseño de experimentos', '2015887')]],
 'Fitomejoramiento': [[('Génetica general', '2015895')],
                      [('Diseño de experimentos', '2015887')]],
 'Fitopatología': [[('Fundamentos de ecología', '1000011-B')],
                   [('Diseño de experimentos', '2015887')],
                   [('Microbiología', '2015903')]],
 'Fundamentos de ecología': [[(('Ninguno', None), None)]],
 'Fundamentos de mecánica': [[('Cálculo diferencial', '1000004-B')]],
 'Geomática básica': [[('Química básica', '1000041-B')],[('Cálculo diferencial', '1000004-B')],[('Biología de plantas', '2015877')]],
 'Gestión agroempresarial': [[('Economía agraria', '2015888')]],
 'Génetica general': [[('Biología Celular y Molecular Básica', '2015882')]],
 'Inglés I - Semestral': [[(('Examen de inglés', None), None)]],
 'Inglés II - Semestral': [[(('Inglés I - Semestral', None), None)]],
 'Inglés III - Semestral': [[('Inglés II - Semestral', '1000045-B')]],
 'Inglés IV - Semestral': [[('Inglés III - Semestral', '1000046-B')]],
 'Introducción a la ingeniería agronómica': [[(('Ninguno', None), None)]],
 'Laboratorio de bioquímica básica': [[(('Ninguno', None), None)]],
 'Laboratorio de química básica': [[(('Ninguno', None), None)]],
 'Lecto-Escritura': [[(('Ninguno', None), None)]],
 'Manejo Integrado de Enfermedades': [[('Fitopatología', '2015894')],
                                      [('Fisiología de la producción vegetal','2015891')]],
 'Manejo de la fertilidad del suelo': [[('Edafología', '2015889')],
                                       [('Fisiología de la producción vegetal','2015891')],
                                       [('Reproducción y multiplicación','2015907')]],
 'Manejo integrado de malezas': [[('Fundamentos de ecología', '1000011-B')],
                                 [('Fisiología de la producción vegetal','2015891')],
                                 [('Botánica taxonómica', '2015878')]],
 'Manejo integrado de plagas': [[('Entomología', '2015890')],
                                [('Fisiología de la producción vegetal', '2015891')]],
 'Matemáticas Básicas': [[(('Ninguno', None), None)]],
 'Mecanización agrícola': [[('Edafología', '2015889')],
                           [('Fundamentos de mecánica', '1000019-B')]],
 'Microbiología': [[(('Ninguno', None), None)]],
 'Práctica Profesional': [[('Agroecosistemas y Sistemas de Producción', '2015881')],
                          [('Ciclo  II: Ejecución de un proyecto productiv', '2015884')]],
 'Química básica': [[(('Ninguno', None), None)]],
 'Reproducción y multiplicación': [[('Fisiología vegetal básica', '2015892')]],
 'Riegos y drenajes': [[('Agroclimatología', '2015880')],
                       [('Cálculo Integral', '1000005-B')],
                       [('Fundamentos de mecánica', '1000019-B')],
                       [('Edafología', '2015889')]],
 'Sociología Rural': [[('inducción a la ingeniería agronómica', None)]],
 'Tecnología de la Poscosecha': [[('Fisiología de la producción vegetal','2015891')],
                                 [('Microbiología', '2015903')]],
 'Trabajo de Grado': [[('Ciclo i: formulación y evaluación de proyect', '2015883')]]
 }