
# ==========================================
# 1. BASES DE DATOS DE ASIGNATURAS
# ==========================================

malla_curricular = {
    'Agroclimatología': {'codigo': '2015880', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Disciplinar'},
    'Agroecosistemas y Sistemas de Producción': {'codigo': '2015881', 'creditos': 3, 'semestre': 8, 'tipo_asignatura': 'Disciplinar'},
    'Bioestadística fundamental': {'codigo': '1000012-B', 'creditos': 3, 'semestre': 3, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Biología Celular y Molecular Básica': {'codigo': '2015882', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Biología de plantas': {'codigo': '2015877', 'creditos': 3, 'semestre': 1, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Bioquímica básica': {'codigo': '1000042-B', 'creditos': 3, 'semestre': 3, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Botánica taxonómica': {'codigo': '2015878', 'creditos': 3, 'semestre': 2, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Ciclo  II: Ejecución de un proyecto productiv': {'codigo': '2015884', 'creditos': 3, 'semestre': 9, 'tipo_asignatura': 'Disciplinar'},
    'Ciclo i: formulación y evaluación de proyect': {'codigo': '2015883', 'creditos': 3, 'semestre': 8, 'tipo_asignatura': 'Disciplinar'},
    'Ciencia del suelo': {'codigo': '2015885', 'creditos': 3, 'semestre': 3, 'tipo_asignatura': 'Disciplinar'},
    'Cálculo Integral': {'codigo': '1000005-B', 'creditos': 4, 'semestre': 2, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Cálculo diferencial': {'codigo': '1000004-B', 'creditos': 4, 'semestre': 1, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Diseño de experimentos': {'codigo': '2015887', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Economía agraria': {'codigo': '2015888', 'creditos': 3, 'semestre': 6, 'tipo_asignatura': 'Disciplinar'},
    'Edafología': {'codigo': '2015889', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Disciplinar'},
    'Entomología': {'codigo': '2015890', 'creditos': 3, 'semestre': 6, 'tipo_asignatura': 'Disciplinar'},
    'Fisiología de la producción vegetal': {'codigo': '2015891', 'creditos': 3, 'semestre': 6, 'tipo_asignatura': 'Disciplinar'},
    'Fisiología vegetal básica': {'codigo': '2015892', 'creditos': 3, 'semestre': 5, 'tipo_asignatura': 'Disciplinar'},
    'Fitomejoramiento': {'codigo': '2015893', 'creditos': 3, 'semestre': 8, 'tipo_asignatura': 'Disciplinar'},
    'Fitopatología': {'codigo': '2015894', 'creditos': 3, 'semestre': 6, 'tipo_asignatura': 'Disciplinar'},
    'Fundamentos de ecología': {'codigo': '1000011-B', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Fundamentos de mecánica': {'codigo': '1000019-B', 'creditos': 3, 'semestre': 2, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Geomática básica': {'codigo': '2015896', 'creditos': 3, 'semestre': 3, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Gestión agroempresarial': {'codigo': '2015922', 'creditos': 3, 'semestre': 7, 'tipo_asignatura': 'Disciplinar'},
    'Génetica general': {'codigo': '2015895', 'creditos': 3, 'semestre': 5, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Inglés I- Semestral': {'codigo': '1000044-B', 'creditos': 2, 'semestre': 1, 'tipo_asignatura': 'Nivelación'},
    'Inglés II - Semestral': {'codigo': '1000045-B', 'creditos': 2, 'semestre': 2, 'tipo_asignatura': 'Nivelación'},
    'Inglés III - Semestral': {'codigo': '1000046-B', 'creditos': 2, 'semestre': 3, 'tipo_asignatura': 'Nivelación'},
    'Inglés IV- Semestral': {'codigo': '1000047-B', 'creditos': 2, 'semestre': 4, 'tipo_asignatura': 'Nivelación'},
    'Introducción a la ingeniería agronómica': {'codigo': '2015897', 'creditos': 2, 'semestre': 1, 'tipo_asignatura': 'Disciplinar'},
    'Laboratorio de bioquímica básica': {'codigo': '1000043-B', 'creditos': 2, 'semestre': 3, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Laboratorio de química básica': {'codigo': '2015782', 'creditos': 2, 'semestre': 2, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Lecto-Escritura': {'codigo': '1000002-B', 'creditos': 2, 'semestre': 1, 'tipo_asignatura': 'Nivelación'},
    'Manejo Integrado de Enfermedades': {'codigo': '2015899', 'creditos': 3, 'semestre': 7, 'tipo_asignatura': 'Disciplinar'},
    'Manejo de la fertilidad del suelo': {'codigo': '2015898', 'creditos': 3, 'semestre': 7, 'tipo_asignatura': 'Disciplinar'},
    'Manejo integrado de malezas': {'codigo': '2015900', 'creditos': 3, 'semestre': 7, 'tipo_asignatura': 'Disciplinar'},
    'Manejo integrado de plagas': {'codigo': '2015901', 'creditos': 3, 'semestre': 7, 'tipo_asignatura': 'Disciplinar'},
    'Matemáticas Básicas': {'codigo': '1000001-B', 'creditos': 3, 'semestre': 1, 'tipo_asignatura': 'Nivelación'},
    'Mecanización agrícola': {'codigo': '2015902', 'creditos': 3, 'semestre': 5, 'tipo_asignatura': 'Disciplinar'},
    'Microbiología': {'codigo': '2015903', 'creditos': 3, 'semestre': 4, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Práctica Profesional': {'codigo': '2015934', 'creditos': 6, 'semestre': 10, 'tipo_asignatura': 'Disciplinar'},
    'Química básica': {'codigo': '1000041-B', 'creditos': 3, 'semestre': 1, 'tipo_asignatura': 'Fund. Obligatoria'},
    'Reproducción y multiplicación': {'codigo': '2015907', 'creditos': 3, 'semestre': 6, 'tipo_asignatura': 'Disciplinar'},
    'Riegos y drenajes': {'codigo': '2015908', 'creditos': 3, 'semestre': 5, 'tipo_asignatura': 'Disciplinar'},
    'Sociología Rural': {'codigo': '2015909', 'creditos': 2, 'semestre': 5, 'tipo_asignatura': 'Disciplinar'},
    'Tecnología de la Poscosecha': {'codigo': '2015910', 'creditos': 3, 'semestre': 8, 'tipo_asignatura': 'Disciplinar'},
    'Trabajo de Grado': {'codigo': '2015291', 'creditos': 6, 'semestre': 10, 'tipo_asignatura': 'Disciplinar'}
}

optativas_produccion = {
    "Produccion de cultivos de clima calido": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
    "Producción de frutales": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
    "Producción de hortalizas": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
    "Producción de ornamentales": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
    "Cultivos perennes industriales": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
    "Producción de papa": {"semestre": 9, "creditos": 3, "tipo_asignatura": "Optativa de Producción"},
}

asignaturas_extra = {
    "Agroecología": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Agrobiodiversidad": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Bioprocesos Agroalimentarios": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Computación estadística": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Desarrollo Rural": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Emprendimiento e innovación en agronegocios": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Evolución y ecología de patógenos de plantas": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Fundamentos de Agroindustria": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Genética de Insectos de Interés económico": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Gestión ambiental agropecuaria": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Investigación de Mercados": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Nutrición Mineral de Plantas": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Producción de cannabis medicinal": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Suelos vivos": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"},
    "Sistemas Agroalimentarios Vinculo entre ambiente, sociedad y desarrollo": {"semestre": None, "Creditos": 3, "tipo_asignatura": "Libre Elección"}
}

asignaturas_posgrado = {
    "Agroclimatología y cambio climático": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Agua y nutrición mineral": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Biología de suelos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Biología molecular": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Biología y ecología de malezas": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Clínica de plantas": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Decisiones de manejo fitosanitario: aproximación práctica": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Degradación química del suelo": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Fertilizantes y fertilización": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Física de suelos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Fisiología avanzada en frutales": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Fisiología de cultivos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Fisiología del desarrollo": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Fitopatología avanzada": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Genética avanzada": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Hongos y nemátodos fitopatógenos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Métodos multivariados": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Pedología": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Recursos genéticos vegetales": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Taxonomía de insectos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Desarrollo económico del territorio rural": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Desarrollo rural y territorios": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Economía de la empresa agraria y alimentaria": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Gestión contable financiera": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Gestión de agroproyectos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Mercadeo agroalimentario y territorial": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Problemas agrarios colombianos": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Sociedad e instituciones rurales": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Geoestadística": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Geomática general": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Geoprocesamiento": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Percepción remota": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
    "Programación sig": {"semestre": None, "Creditos": 4, "tipo_asignatura": "Posgrado"},
}
