prerequisitos = {'Agroclimatología': [[(('Ninguno', None), None)],'AND'],
 'Agroecosistemas y Sistemas de Producción': [[('Fisiología de la producción vegetal','2015891')],
                                              [('Entomología', '2015890')],
                                              [('Fitopatología', '2015894')],
                                              [('Edafología', '2015889')],'AND'],
 'Bioestadística fundamental': [[('Cálculo diferencial', '1000004-B')],'AND'],
 'Biología Celular y Molecular Básica': [[('Bioquímica básica', '1000042-B')],'AND'],
 'Biología de plantas': [[(('Ninguno', None), None)],'AND'],
 'Bioquímica básica': [[('Química básica', '1000041-B')],'AND'],
 'Botánica taxonómica': [[('Biología de plantas', '2015877')],'AND'],
 'Ciclo  II: Ejecución de un proyecto productiv': [[('Ciclo i: formulación y evaluación de proyect', '2015883')],'AND'],
 'Ciclo i: formulación y evaluación de proyect': [[('Riegos y drenajes','2015908')],
                                                  [('Mecanización agrícola','2015902')],
                                                  [('Manejo de la fertilidad del suelo','2015898')],
                                                  [('Manejo integrado de plagas','2015901')],
                                                  [('Manejo Integrado de Enfermedades','2015899')],
                                                  [('Manejo integrado de malezas','2015900')],'AND'],
 'Ciencia del suelo': [[('Laboratorio de química básica', '2015782')],'AND'],
 'Cálculo Integral': [[('Cálculo diferencial', '1000004-B')],'AND'],
 'Cálculo diferencial': [[(('Ninguno', None), None)],'AND'],
 'Diseño de experimentos': [[('Bioestadística fundamental', '1000012-B')],
                            [('Probabilidad y Estadística Fundamental','1000013-B')],'OR'],
 'Economía agraria': [[('Cálculo Integral', '1000005-B')],
                      [('Sociología Rural', '2015909')],'AND'],
 'Edafología': [[('Ciencia del suelo', '2015885')],'AND'],
 'Entomología': [[('Génetica general', '2015895')],
                 [('Fundamentos de ecología', '1000011-B')],'AND'],
 'Fisiología de la producción vegetal': [[('Fisiología vegetal básica','2015892')],'AND'],
 'Fisiología vegetal básica': [[('Botánica taxonómica', '2015878')],
                               [('Biología Celular y Molecular Básica','2015882')],
                               [('Diseño de experimentos', '2015887')],'AND'],
 'Fitomejoramiento': [[('Génetica general', '2015895')],
                      [('Diseño de experimentos', '2015887')],'AND'],
 'Fitopatología': [[('Fundamentos de ecología', '1000011-B')],
                   [('Diseño de experimentos', '2015887')],
                   [('Microbiología', '2015903')],'AND'],
 'Fundamentos de ecología': [[(('Ninguno', None), None)],'AND'],
 'Fundamentos de mecánica': [[('Cálculo diferencial', '1000004-B')],'AND'],
 'Geomática básica': [[('Química básica', '1000041-B')],
                      [('Cálculo diferencial', '1000004-B')],
                      [('Biología de plantas', '2015877')],'AND'],
 'Gestión agroempresarial': [[('Economía agraria', '2015888')],'AND'],
 'Génetica general': [[('Biología Celular y Molecular Básica', '2015882')],'AND'],
 'Inglés I - Semestral': [[(('Examen de inglés', None), None)],'AND'],
 'Inglés II - Semestral': [[(('Inglés I - Semestral', None), None)],'AND'],
 'Inglés III - Semestral': [[('Inglés II - Semestral', '1000045-B')],'AND'],
 'Inglés IV - Semestral': [[('Inglés III - Semestral', '1000046-B')],'AND'],
 'Introducción a la ingeniería agronómica': [[(('Ninguno', None), None)],'AND'],
 'Laboratorio de bioquímica básica': [[('Laboratorio de química básica','2015782')],[('Química básica', '1000041-B')],'AND'],
 'Laboratorio de química básica': [[(('Ninguno', None), None)],'AND'],
 'Lecto-Escritura': [[(('Ninguno', None), None)],'AND'],
 'Manejo Integrado de Enfermedades': [[('Fitopatología', '2015894')],
                                      [('Fisiología de la producción vegetal','2015891')],'AND'],
 'Manejo de la fertilidad del suelo': [[('Edafología', '2015889')],
                                       [('Fisiología de la producción vegetal','2015891')],
                                       [('Reproducción y multiplicación','2015907')],'AND'],
 'Manejo integrado de malezas': [[('Fundamentos de ecología', '1000011-B')],
                                 [('Fisiología de la producción vegetal','2015891')],
                                 [('Botánica taxonómica', '2015878')],'AND'],
 'Manejo integrado de plagas': [[('Entomología', '2015890')],
                                [('Fisiología de la producción vegetal', '2015891')],'AND'],
 'Matemáticas Básicas': [[(('Ninguno', None), None)],'AND'],
 'Mecanización agrícola': [[('Edafología', '2015889')],
                           [('Fundamentos de mecánica', '1000019-B')],'AND'],
 'Microbiología': [[('Laboratorio bioquímica básica', '1000043-B')],'AND'],
 'Práctica Profesional': [[('Agroecosistemas y Sistemas de Producción', '2015881')],
                          [('Ciclo  II: Ejecución de un proyecto productiv', '2015884')],'AND'],
 'Probabilidad y Estadística Fundamental': [[('Cálculo diferencial', '1000004-B')],'AND'],
 'Química básica': [[(('Ninguno', None), None)],'AND'],
 'Reproducción y multiplicación': [[('Fisiología vegetal básica', '2015892')],'AND'],
 'Riegos y drenajes': [[('Agroclimatología', '2015880')],
                       [('Cálculo Integral', '1000005-B')],
                       [('Fundamentos de mecánica', '1000019-B')],
                       [('Edafología', '2015889')],'AND'],
 'Sociología Rural': [[('inducción a la ingeniería agronómica', None)],'AND'],
 'Tecnología de la Poscosecha': [[('Fisiología de la producción vegetal','2015891')],
                                 [('Microbiología', '2015903')],'AND'],
 'Trabajo de Grado': [[('Ciclo i: formulación y evaluación de proyect', '2015883')],'AND'],
 'Trabajo de Grado - Asignaturas de Posgrado': [[('Ciclo i: formulación y evaluación de proyect', '2015883')],'AND']
 }